version: '3'

services:
  app:
    profiles: ['devcontainer']
    container_name: ejs-central-dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
    depends_on:
      - dev-db
    stdin_open: true
    tty: true
    environment:
      DEVCONTAINER: 1
    network_mode: host
  dev-db:
    container_name: ejs-central-dev-db
    image: postgres:14-alpine
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: skku
